### ISSUE TITLE
Error on flutter web ("Refused to set unsafe header content-length")

### ISSUE THREAD

**Issue by galvin59** [kkazuo/dart-azblob#14] opened 2024-01-12 10:00 UTC
Hi,

I was using azblob without a problem, but now, on flutter web, I get the following errors when trying to upload a file :
"Refused to set unsafe header content-length"
followed by :
"Server failed to authenticate the request" 

Any idea of the origin / workaround ?
Thanks

Julien

**Comment by galvin59** [comment] 2024-01-12 10:06
reverting to 2.6.0 seems to fix the issue, but this remains on 3.0.x

**Comment by kkazuo** [comment] 2024-01-12 10:18
Hmmm..
It’s probably caused by `universal_io`.
So I’m going to revert to 2.6.0 line for next ver.

By the way, could you please tell more error details?
Do you use `putBlob` for file upload?
How large your data size? And data type is string or binary?

Thank you,

**Comment by kkazuo** [comment] 2024-01-12 10:30
In my opinion, this issue is dup of #12.
So I close this issue now.
Please don’t hesitate to reopen if you think it does not.
Or you can discuss on issue #12.

Thank you

**Closed by kkazuo** 2024-01-12 10:30 UTC

**Comment by galvin59** [comment] 2024-01-12 13:44
the picture is pretty small <500k
I only get those two errors in the js console, not much more to share ...
any way reverting did the trick for me !
